# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5ae5229619a3ac0efae2fd5c96d0a3ba3bb6c4ca1725dbd754d912a46f90dfa6cd0a14611d3a4d30c76f0fa24d7c2aafaaa48a178fe7852d1057a8a079cd2ff0

test:
  secret_key_base: 774b627f3fb55cddc9c0b2182f69a3a75eac0b231572f763f44c829f817ffb95409e2cb3e94d4f89867a9bcf13b7a8e5a5c36d7f9a91a9fb42f5dbb304811778

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
